POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "grace.hopper@systers.xyz",
    "password": "123456"
}

GET http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY1MDIzMzkwOSwiZXhwIjoxNjUwMjM3NTA5LCJzdWIiOiIyIn0.nS99u-MBatZHbexMUenwsGdS8oV55BIaGwI6PSP7BC8

GET http://localhost:8080/products HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY3MDc5NTk4MiwiZXhwIjoxNjcwNzk5NTgyLCJzdWIiOiIyIn0.We_viBZvqs-GsA0HAgCUSTkPWhA5AAV6_eWnT_s3hdc

GET http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY1MDIzMzkwOSwiZXhwIjoxNjUwMjM3NTA5LCJzdWIiOiIyIn0.nS99u-MBatZHbexMUenwsGdS8oV55BIaGwI6PSP7BC8

PATCH http://localhost:8080/orders/2 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY1MDIzNDAzNSwiZXhwIjoxNjUwMjM3NjM1LCJzdWIiOiIyIn0.q6lDwW_wyK6-8-lUyiLUwnoowRLsvuFblu1yufkaa_Q

{
    "status": "delivered",
    "dateProcessed": "2022-03-05 16:00"
}

POST http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY2NjEyNTQ5NSwiZXhwIjoxNjY2MTI5MDk1LCJzdWIiOiIyIn0.laNI7HKXIcDzCp1AYl4aMWh5jSlcMFKFQLHrCC2XTPw

{
    "client": "Harry Potter",
    "products": [
        {
            "qty": 1,
            "product": {
            "id": 1,
            "name": "Sandwich de jamón y queso",
            "price": 1000,
            "image": "https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api/resources/images/sandwich.jpg",
            "type": "Desayuno",
            "dateEntry": "2022-03-05 15:14:10"
            }
        },
        {
            "qty": 1,
            "product": {
            "id": 2,
            "name": "Café americano",
            "price": 500,
            "image": "https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api/resources/images/coffe.jpg",
            "type": "Desayuno",
            "dateEntry": "2022-03-05 15:14:10"
            }
        }
    ],
    "status": "pending",
    "dataEntry": "2022-03-05 15:00"
}

POST http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY2OTg0MzU1MCwiZXhwIjoxNjY5ODQ3MTUwLCJzdWIiOiIyIn0.pMi6MF0qmgZSfTzV6Lo3Hm9QWmrPd2v2egkCjIadJX8

{
  "email": "mesero@burger.com",
  "password": "123456",
  "role": "mesero"
}

POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "mesero@burger.com",
    "password": "123456"
}

GET http://localhost:8080/products HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY3MDc4MzQ2MSwiZXhwIjoxNjcwNzg3MDYxLCJzdWIiOiIyIn0.y1Yp_yAYMMKH9HVn6O69D90egWNeo2a2h1fyCKcpWI4

{
  "name": "Café Americano",
  "price": 5,
  "image": "https://ibb.co/19HRwsQ",
  "type": "Desayuno"
}

POST http://localhost:8080/products/5 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY3MDc5NTkyMSwiZXhwIjoxNjcwNzk5NTIxLCJzdWIiOiIyIn0.gXluapfbUgrvznPNaRS3QMZUA-G_G-SQF0nboy2JIaw

{
    "name": "Café Americano",
    "price": 5,
    "image": "https://ibb.co/19HRwsQ",
    "type": "Desayuno",
    "id": 5
}

}

curl -X 'DELETE' \
  'https://virtserver.swaggerhub.com/ssinuco/BurgerQueenAPI/2.0.0/products/5' \
  -H 'accept: application/json'




